### ISSUE TITLE
Port 

### ISSUE THREAD

**Issue by questluv** [ramsaylanier/VuePress#5]
I resolved the port problem but I have another problem. When I try 'yarn start' I got this message below.
Error: Cannot find module '/opt/bitnami/apps/VuePress/scripts/start'

**Comment by ramsaylanier** [comment]
@questluv I've updated the whole script process so now you should just need to run `npm run serve` after `npm install`

**Comment by questluv** [comment]
1. 'npm' didn't work but when I tried 'yarn' it works. However, I just followed your instruction and it kept saying that I need 'client.json' even thought I created 'deveopment.json' and 'production.json'.

2. Can you let me know how to execute the server after running 'npm start'.
I mean running 'npm run serve' shows the ':8080' port but I don't know how it works with 'npm start'.

Sorry if I don't explain well! I am new to express.js and node.js.

Thank you!

**Comment by ramsaylanier** [comment]
@questluv First things first - have you cloned the [WordExpress Server](https://github.com/ramsaylanier/WordExpress-Server) repo and have that running? Also, yes, you should create a `client.json` instead of `development.json` and `production.json`.  I forgot to update the readme. Sorry!

**Comment by questluv** [comment]
@ramsaylanier Thank you for your reply! Yes, I cloned the WordExpress Server and it's running now.
Also I created 'client.json' but it seems now I need to use 'http:/localhost:4000/graphql' rather than 'http:/localhost:4000'. 

Everything is fine when I run 'npm run serve' but when I try 'npm start', I got this message below and I don't really know what I need to do with it. 

$ node server.js 
[HPM] Proxy created: /  ->  http://localhost/8080
[HPM] Proxy created: /  ->  http://localhost/8080
[HPM] Proxy created: /  ->  http://localhost/8080

**Comment by ramsaylanier** [comment]
@questluv  Ah, my fault - for now, running `yarn serve` starts the development server. `npm run start` isn't a thing right now. I'm working on updating the production stuff so that's going to change. For now, just use `yarn serve`
