### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by coreysyms** [ramsaylanier/VuePress#7]
Hello.
Thank you for this work first. I hope to get it working.

I have successfully set up and connected the WordExpress-Server, it is running on port 4000. But I can't get this starter to run because of missing modules.

`Error: Cannot find module 'webpack'`

So I say, ok, let's just in stall webpack `npm install webpack`
Then I get a missing module for `babel-loader`, then `eslint` then `eslint something else` and so on.

I figure something is missing here as this rabbit hole appears deep. Any help you could provide would be awesome! Thanks.

**Comment by thomascallahan** [comment]
Same here. I went down the rabbit hole and it appears to be bottomless, no matter how many missing packages I install it asks for more. npm install also outputs a bunch of warning about missing peer packages that I have to install manually. Seems like package.json for this project is broken.

I had to run

npm install webpack
npm install eslint@4.0.0
npm install graphql@0.13.0
npm install graphql@0.13.1
    (package.json includes 0.14 release candidate but there are other packages that specifically list only 11, 12, 13 or 13.1)
npm install apollo-client
npm install --save-dev @babel/core@7.0.0

But when I did that I got like 30 dependency errors saying packages needed babel/core 7.0.0 beta 47. If I install that, I get just one error but babel-loader requires babel/core 7.0.0 (not the beta). So there are two mutually-exclusive dependency errors.

**Comment by questluv** [comment]
The instruction here is really confusing. Don't use npm install. Use yarn instead. And don't create 'config.json'. Create 'client.json' instead.

**Comment by ramsaylanier** [comment]
@coreysyms @thomascallahan sorry for the delay in response and confusing directions. I've updated the README. @questluv is correct, use yarn to install.

**Comment by coreysyms** [comment]
Thanks. I’ll give yarn a whirl.

**Comment by questluv** [comment]
Hey @ramsaylanier  Thanks for updating! However when I try 'yarn start', I got this error. 

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/opt/bitnami/apps/wordexpress-starter-vue/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

**Comment by questluv** [comment]
Hey, I just realized that I need to create 'production.json' file in the config folder when I try 'yarn start'
However, now I got this error. 

error during render : /
TypeError: Object(...) is not a function
    at Module.3ad4 (src/themes/basic/components/post/containers/PostsContainer.vue:14:0)
    at t (webpack/bootstrap:33:0)
    at module.exports.000b (webpack:/external "core-js/modules/es7.promise.finally":1:0)
    at Object.<anonymous> (webpack:/external "core-js/modules/es7.promise.finally":1:0)
    at evaluateModule (/opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8349:21)
    at /opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8407:18
    at new Promise (<anonymous>)
    at /opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8399:14
    at Object.renderToString (/opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8575:9)
    at app.get (/opt/bitnami/apps/wordexpress-starter-vue/server.js:74:12)
error during render : /favicon.ico
TypeError: Cannot redefine property: $filesRoot
    at Function.defineProperty (<anonymous>)
    at Module.3ad4 (src/core/vue-apollo.js:26:7)
    at t (webpack/bootstrap:33:0)
    at module.exports.000b (webpack:/external "core-js/modules/es7.promise.finally":1:0)
    at Object.<anonymous> (webpack:/external "core-js/modules/es7.promise.finally":1:0)
    at evaluateModule (/opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8349:21)
    at /opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8407:18
    at new Promise (<anonymous>)
    at /opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8399:14
    at Object.renderToString (/opt/bitnami/apps/wordexpress-starter-vue/node_modules/vue-server-renderer/build.js:8575:9)

**Comment by questluv** [comment]
Got another error when I try 'yarn serve'. 

 warning  in ./src/themes/basic/components/post/containers/PostsContainer.vue?vue&type=script&lang=js&

"export 'willPrefetch' was not found in 'vue-apollo'

**Comment by questluv** [comment]
Has anybody succeeded to run?

**Comment by coreysyms** [comment]
I have not sat down with this yet. I will this week

**Comment by ramsaylanier** [comment]
@questluv I believe I've fixed the issue with my two most recent commits.
